### ISSUE TITLE
NoMethodError on ruby 2.4.1

### ISSUE THREAD

**Issue by drakeltheryuujin** [siorai/RubyResumeApp#1]
When running the app via:
`ruby resume.rb -s 'https://kandi.ladancesafe.org' -u 'FlatironSchoolRep' -p '[redacted]'`

Receiving error message: 

```
resume.rb:13:in `block in initialize': undefined method `append' for []:Array (NoMethodError)
	from resume.rb:12:in `each'
	from resume.rb:12:in `initialize'
	from resume.rb:136:in `new'
	from resume.rb:136:in `<main>'
```

ruby --version
`ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]`

**Comment by siorai** [comment]
Awesome. Thanks.  

Fixed in afd9a20da745e4c6f85b7ddf8f8e9b3d1683dfe3.  Swapping append() methods for push() methods made this work in both current 2.6.2 as of this writing and 2.4.2.
